[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
zoot = "DXDfRWEqpRLzsX8WRdBYHLseATeAEqAFGXtbqhPv4vr4"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "https://api.devnet.solana.com"
ANCHOR_WALLET = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
